// Mapping name keyword → Iconify icon ID (Google Noto pack — high-fidelity SVG).
// Order matters: more specific keywords first.
const norm = (s: string) =>
  s.toLowerCase().trim().normalize("NFD").replace(/[̀-ͯ]/g, "");

const KEYWORD_TO_ICON: Array<[string, string]> = [
  // Meats — specific FR cuts first
  ["merguez", "noto:hot-dog"],
  ["chipo", "noto:hot-dog"],
  ["saucisse", "noto:hot-dog"],
  ["pilon", "noto:poultry-leg"],
  ["aile de poulet", "noto:poultry-leg"],
  ["aile", "noto:poultry-leg"],
  ["poulet", "noto:poultry-leg"],
  ["dinde", "noto:poultry-leg"],
  ["cote de porc", "noto:cut-of-meat"],
  ["cote de boeuf", "noto:cut-of-meat"],
  ["côte", "noto:cut-of-meat"],
  ["cote", "noto:cut-of-meat"],
  ["porc", "noto:cut-of-meat"],
  ["entrecote", "noto:cut-of-meat"],
  ["bavette", "noto:cut-of-meat"],
  ["agneau", "noto:cut-of-meat"],
  ["mouton", "noto:cut-of-meat"],
  ["boeuf", "noto:cut-of-meat"],
  ["canard", "noto:duck"],
  ["magret", "noto:duck"],
  ["brochette", "noto:cooking"],
  ["steak hache", "noto:hamburger"],
  ["burger", "noto:hamburger"],
  ["hamburger", "noto:hamburger"],
  ["bacon", "noto:bacon"],
  ["lard", "noto:bacon"],
  ["crevette", "noto:shrimp"],
  ["poisson", "noto:fish"],
  ["saumon", "noto:fish"],
  ["sardine", "noto:fish"],
  ["steak", "noto:cut-of-meat"],

  // Sides
  ["mais", "noto:ear-of-corn"],
  ["maïs", "noto:ear-of-corn"],
  ["salade verte", "noto:green-salad"],
  ["salade", "noto:green-salad"],
  ["tomate", "noto:tomato"],
  ["concombre", "noto:cucumber"],
  ["poivron", "noto:bell-pepper"],
  ["aubergine", "noto:eggplant"],
  ["courgette", "noto:cucumber"],
  ["champignon", "noto:mushroom"],
  ["pomme de terre", "noto:potato"],
  ["patate", "noto:potato"],
  ["frite", "noto:french-fries"],
  ["pain", "noto:baguette-bread"],
  ["baguette", "noto:baguette-bread"],
  ["fromage", "noto:cheese-wedge"],
  ["camembert", "noto:cheese-wedge"],
  ["chevre", "noto:cheese-wedge"],
  ["œuf", "noto:egg"],
  ["oeuf", "noto:egg"],
  ["riz", "noto:cooked-rice"],
  ["pates", "noto:spaghetti"],
  ["pâtes", "noto:spaghetti"],
  ["taboule", "noto:green-salad"],
  ["coleslaw", "noto:green-salad"],
  ["chips", "noto:french-fries"],

  // Drinks
  ["pression", "noto:beer-mug"],
  ["biere", "noto:beer-mug"],
  ["bière", "noto:beer-mug"],
  ["vin rouge", "noto:wine-glass"],
  ["vin blanc", "noto:wine-glass"],
  ["rose", "noto:wine-glass"],
  ["rosé", "noto:wine-glass"],
  ["vin", "noto:wine-glass"],
  ["champagne", "noto:bottle-with-popping-cork"],
  ["whisky", "noto:tumbler-glass"],
  ["mojito", "noto:tropical-drink"],
  ["cocktail", "noto:cocktail-glass"],
  ["coca", "noto:cup-with-straw"],
  ["soda", "noto:cup-with-straw"],
  ["limonade", "noto:cup-with-straw"],
  ["jus", "noto:beverage-box"],
  ["eau", "noto:potable-water"],
  ["cafe", "noto:hot-beverage"],
  ["café", "noto:hot-beverage"],
  ["the", "noto:teacup-without-handle"],
  ["thé", "noto:teacup-without-handle"],

  // Desserts
  ["glace", "noto:ice-cream"],
  ["sorbet", "noto:shaved-ice"],
  ["gateau", "noto:shortcake"],
  ["gâteau", "noto:shortcake"],
  ["tarte", "noto:pie"],
  ["chocolat", "noto:chocolate-bar"],
  ["fraise", "noto:strawberry"],
  ["pomme", "noto:red-apple"],
  ["banane", "noto:banana"],
  ["pasteque", "noto:watermelon"],
  ["pastèque", "noto:watermelon"],
  ["melon", "noto:melon"],
  ["fruit", "noto:strawberry"],

  // Generic fallback
  ["bbq", "noto:fire"],
  ["barbecue", "noto:fire"],
];

const EMOJI_TO_ICON: Record<string, string> = {
  "🌭": "noto:hot-dog",
  "🍗": "noto:poultry-leg",
  "🥩": "noto:cut-of-meat",
  "🥓": "noto:bacon",
  "🍔": "noto:hamburger",
  "🍖": "noto:meat-on-bone",
  "🍢": "noto:oden",
  "🦆": "noto:duck",
  "🐑": "noto:ewe",
  "🦐": "noto:shrimp",
  "🐟": "noto:fish",
  "🍤": "noto:fried-shrimp",
  "🌽": "noto:ear-of-corn",
  "🥗": "noto:green-salad",
  "🥒": "noto:cucumber",
  "🍅": "noto:tomato",
  "🍆": "noto:eggplant",
  "🫑": "noto:bell-pepper",
  "🍄": "noto:mushroom",
  "🥔": "noto:potato",
  "🍟": "noto:french-fries",
  "🥖": "noto:baguette-bread",
  "🧀": "noto:cheese-wedge",
  "🥚": "noto:egg",
  "🍚": "noto:cooked-rice",
  "🍝": "noto:spaghetti",
  "🍺": "noto:beer-mug",
  "🍷": "noto:wine-glass",
  "🍾": "noto:bottle-with-popping-cork",
  "🥂": "noto:clinking-glasses",
  "🥃": "noto:tumbler-glass",
  "🍹": "noto:tropical-drink",
  "🍸": "noto:cocktail-glass",
  "🥤": "noto:cup-with-straw",
  "🧃": "noto:beverage-box",
  "💧": "noto:potable-water",
  "☕": "noto:hot-beverage",
  "🍵": "noto:teacup-without-handle",
  "🍦": "noto:soft-ice-cream",
  "🍧": "noto:shaved-ice",
  "🍰": "noto:shortcake",
  "🥧": "noto:pie",
  "🍫": "noto:chocolate-bar",
  "🍓": "noto:strawberry",
  "🍎": "noto:red-apple",
  "🍌": "noto:banana",
  "🍉": "noto:watermelon",
  "🍈": "noto:melon",
  "🔥": "noto:fire",
};

export function iconForItem(name: string, emoji?: string): string {
  const n = norm(name);
  for (const [kw, icon] of KEYWORD_TO_ICON) {
    if (n.includes(norm(kw))) return icon;
  }
  if (emoji && EMOJI_TO_ICON[emoji]) return EMOJI_TO_ICON[emoji];
  return "noto:cut-of-meat";
}
